events {}

http {
    upstream iot_controllers {
        least_conn;
        server iot-controller:9090;
        server iot-controller-2:9090;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://iot_controllers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
